### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'set_clipboard'

### ISSUE THREAD

**Issue by Praful** [Erotemic/vimtk#5]
Hello

No matter which command I try, I get the following error.

```
Error detected while processing function vimtk#ipython_import_all:
line   93:
Traceback (most recent call last):
  File "<string>", line 89, in <module>
  File "c:\data\LinuxHome\vimfiles\vimplug\vimtk\vimtk\core.py", line 774, in execute_text_in_terminal
    Clipboard.copy(text)
  File "c:\data\LinuxHome\vimfiles\vimplug\vimtk\vimtk\core.py", line 141, in copy
    return cplat.copy_text_to_clipboard(text)
  File "c:\data\LinuxHome\vimfiles\vimplug\vimtk\vimtk\cplat.py", line 162, in copy_text_to_clipboard
    _ensure_clipboard_backend()
  File "c:\data\LinuxHome\vimfiles\vimplug\vimtk\vimtk\cplat.py", line 151, in _ensure_clipboard_backend
    pyperclip.set_clipboard(backend)
AttributeError: 'NoneType' object has no attribute 'set_clipboard'

```

I have installed `ubelt` and `pyperclip` (I couldn't see anything about installing `pyperclip` but installed it when I get a module not found error; you may want to add it the readme unless I missed it).

`<leader>H` outputs:

```
hello world from python
Python in Vim Variables
vim.current.buffer = <buffer >
 * vim.current.buffer.name = 
 * len(vim.current.buffer) = 178
 * row, col) = vim.current.window.cursor = (148, 0)
vim.current.buffer[0] = ''
vim.current.buffer[1] = ''
vim.current.buffer[0:2] = ['', '']
vim.current.buffer[-1] = "AttributeError: 'NoneType' object has no attribute 'set_clipboard'"
buf = <buffer >
buf.mark = <built-in method mark of vim.buffer object at 0x000000001762F370>
buf.mark(<) = None
buf.mark(>) = None
mark a = None
vimtk.__version__ = '0.2.4'
```

I use `vim-plug` to install the plugins:
```
Plug 'sjl/badwolf'
Plug 'Erotemic/vimtk'
```

I am using Windows 10 1909, Python 3.8 and gvim 8.2 (patches 1-369). 

Please let me know what else I need to do to get the plugins to work.

Thanks

Praful

**Comment by Erotemic** [comment]
I definitely need a note about installing pyperclip and the other third party Python requirements. This is my first vim plugin, so there are probably best practices I'm still unaware of. Reporting issues like this will help me shore up that knowledge, so thanks for the contribution!

As far as I can tell, handling python packages inside of vim can be a bit tricky because its not always clear which python environment you are in. The vim python support actually has a bug where `sys.executable` will sometimes report the wrong path. What would be really useful is if vim-plug had some way to manage installing third party python packages so issues like this would arise less frequently. 

Back to your issue. Looking at the code: https://github.com/Erotemic/vimtk/blob/master/vimtk/cplat.py#L9

If python fails to import pyperclip it logs a warning and then sets `pyperclip = None`, which is what must be happening for you. Perhaps you installed pyperclip in a python environment that is different than the one vim is using?

**Comment by Praful** [comment]
Thanks for replying. Here's an update: two other Python packages were missing: `psutil` and `pywinauto`. I've installed both now. This is the new error message:

```
Error detected while processing function vimtk#execute_text_in_terminal:
line   50:
Traceback (most recent call last):
  File "c:\apps\Python\latest3-64\Lib\ctypes\__init__.py", line 123, in WINFUNCTYPE
    return _win_functype_cache[(restype, argtypes, flags)]
KeyError: (<class 'ctypes.HRESULT'>, (<class 'ctypes.c_long'>, <class 'comtypes.automation.tagVARIANT'>, <class 'comtypes.LP_POINTER(IUIAutomationCondition)'>), 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 47, in <module>
  File "c:\data\LinuxHome\vimfiles\vimplug\vimtk\vimtk\core.py", line 782, in execute_text_in_terminal
    import pywinauto
  File "c:\apps\Python\latest3-64\Lib\site-packages\pywinauto\__init__.py", line 89, in <module>
    from . import findwindows
  File "c:\apps\Python\latest3-64\Lib\site-packages\pywinauto\findwindows.py", line 42, in <module>
    from . import controls
  File "c:\apps\Python\latest3-64\Lib\site-packages\pywinauto\controls\__init__.py", line 36, in <module>
    from . import uiawrapper # register "uia" back-end (at the end of uiawrapper module)
  File "c:\apps\Python\latest3-64\Lib\site-packages\pywinauto\controls\uiawrapper.py", line 47, in <module>
    from ..uia_defines import IUIA
  File "c:\apps\Python\latest3-64\Lib\site-packages\pywinauto\uia_defines.py", line 181, in <module>
    pattern_ids = _build_pattern_ids_dic()
  File "c:\apps\Python\latest3-64\Lib\site-packages\pywinauto\uia_defines.py", line 169, in _build_pattern_ids_dic
    if hasattr(IUIA().ui_automation_client, cls_name):
  File "c:\apps\Python\latest3-64\Lib\site-packages\pywinauto\uia_defines.py", line 50, in __call__
    cls._instances[cls] = super(_Singleton, cls).__call__(*args, **kwargs)
  File "c:\apps\Python\latest3-64\Lib\site-packages\pywinauto\uia_defines.py", line 60, in __init__
    self.UIA_dll = comtypes.client.GetModule('UIAutomationCore.dll')
  File "c:\apps\Python\latest3-64\Lib\site-packages\comtypes\client\_generate.py", line 110, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "c:\apps\Python\latest3-64\Lib\site-packages\comtypes\client\_generate.py", line 184, in _CreateWrapper
    mod = _my_import(fullname)
  File "c:\apps\Python\latest3-64\Lib\site-packages\comtypes\client\_generate.py", line 24, in _my_import
    return __import__(fullname, globals(), locals(), ['DUMMY'])
  File "C:\Users\praful\AppData\Roaming\Python\Python38\comtypes_cache\_944DE083_8FB8_45CF_BCB7_C477ACB2F897_0_1_0.py", line 116, in <module>
    IUIAutomation._methods_ = [
  File "c:\apps\Python\latest3-64\Lib\site-packages\comtypes\__init__.py", line 329, in __setattr__
    self._make_methods(value)
  File "c:\apps\Python\latest3-64\Lib\site-packages\comtypes\__init__.py", line 698, in _make_methods
    prototype = WINFUNCTYPE(restype, *argtypes)
  File "c:\apps\Python\latest3-64\Lib\ctypes\__init__.py", line 125, in WINFUNCTYPE
    class WinFunctionType(_CFuncPtr):
TypeError: item 2 in _argtypes_ passes a union by value, which is unsupported.
```

Does that help diagnose the issue? Is there anything else that could help?

Also, could you please confirm which third party Python packages are required?

Thanks

Praful

**Comment by Erotemic** [comment]
The list of required python packages is in `requirements/runtime.txt`, which currently is: 

```
ubelt >= 0.7.1
pyperclip >= 1.7.0
pyflakes >= 2.1.1
six >= 1.11.0
psutil >= 5.4.7
xinspect >= 0.0.3
pywinauto;platform_system=="Windows"
```

I've started looking into seeing if I can get these dependencies to install at plugin install time. I submitted an issue to vim-plug https://github.com/junegunn/vim-plug/issues/949#issuecomment-602113983 to see if its possible (it looks like it will be very difficult). For my reference I also asked a semi-related question here: 
https://vi.stackexchange.com/questions/23264/can-you-use-plugins-inside-of-your-vimrc

In most cases I load third party libraries on demand so if one isn't installed it only complains if you attempt to use the function that requires it (which means other functions still work if there is an issue with a package). 

I've dusted off my windows laptop to test things on my end. Currently things seem to work OK when I use my vimrc environment and pywinauto 0.6.4. I also upgraded to 0.6.8 (and fixed some warnings about SendKeys), and things still seem to work. (although there is a warning about Revert to STA COM threading mode from pywinauto). 

vimtk#execute_text_in_terminal seems to still be working well on my end, but I'd like to understand why its breaking for you. 

One major difference that I'm seeing is that I'm using Miniconda3 for my python executable. My win32 PATH also includes `%USERPROFILE%\Miniconda3`, and my vimrc also contains:

```vim
if has('win32')
    " Fix issue where system() breaks when running from git-bash on win32
    set shell=C:\WINDOWS\system32\cmd.exe
    set pythonthreedll=$HOME_DPATH\Miniconda3\python36.dll
endif
```

but removing these doesn't seem to break anything for me. 

I've added a bit more debugging info to `vimtk#hello_world`, could you re-execute that and paste the results?

It also looks like the error is occurring on the import of `pywinauto`, could you try importing `pywinauto` in a script outside of vim to check that if its a system problem or a vim problem?

**Comment by Praful** [comment]
You were right about the `pywinauto`. When I imported it outside of vim, the same error occurred. I checked github issues for the module and it's related to Python 3.8.1. I installed 3.8.2, as suggested, and the import is working successfully.

When I select a line, eg `print('test')`, the line is sent to `cmd`. If no console exists, `cmd` is opened. This Python command obviously fails to execute in `cmd`. So I ran `ipython` in the console. However, now only `^M` is sent to `cmd`. It turned that's because I'm running `ipython` in vim mode. If I disable that then lines are sent to `ipython` correctly.

Regardless of what I do the following error is shown in vim:

```
Error detected while processing function vimtk#execute_text_in_terminal:
line   50:
c:\data\LinuxHome\vimfiles\vimplug\vimtk\vimtk\core.py:795: DeprecationWarning: Method .SendKeys() is deprecated, use .send_keys() instead.
  pywinauto.keyboard.SendKeys('^v')
c:\data\LinuxHome\vimfiles\vimplug\vimtk\vimtk\core.py:796: DeprecationWarning: Method .SendKeys() is deprecated, use .send_keys() instead.
  pywinauto.keyboard.SendKeys('{ENTER}')
c:\data\LinuxHome\vimfiles\vimplug\vimtk\vimtk\core.py:797: DeprecationWarning: Method .SendKeys() is deprecated, use .send_keys() instead.
  pywinauto.keyboard.SendKeys('{ENTER}')
```

If I select several lines of text in vim and execute them using `<leader>a`, the following error occurs in `ipython`:

```
Unhandled exception in event loop:
  File "c:\apps\python\latest3-64\lib\asyncio\proactor_events.py", line 768, in _loop_self_reading
    f.result()  # may raise
  File "c:\apps\python\latest3-64\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "c:\apps\python\latest3-64\lib\asyncio\windows_events.py", line 457, in finish_recv
    raise ConnectionResetError(*exc.args)

Exception [WinError 995] The I/O operation has been aborted because of either a thread exit or an application request
Press ENTER to continue...   
```

I'm not sure if this has any adverse effect or is cosmetic. It usually occurs when I select a function and send it to the console but I'm not 100% sure. I'll start using it and see how it goes.

So some progress!

If you can get rid of the deprecation warnings and make it work with `ipython` in vim mode, that would make it usable for me! 

To get `ipython` in vim mode, I have the following line in `~\.ipython\profile_default\ipython_config.py`:

```
c.TerminalInteractiveShell.editing_mode = 'vi'
```

Thanks again for your help.

Praful

**Comment by Erotemic** [comment]
As far as those warnings go, I believe I did fix those in my last update. Try `:PlugUpdate` and see if that gets rid of them. 

As for 'vi' mode, that might be trickier to accomplish (because currently the execute_text_in_terminal function is implemented via macros), but I might be able to make a vimtk option such that if it is set, it sends the right escape sequences / paste commands to the cmd window. I'll test in 'vi' mode on my win32 machine and get back to you.

**Comment by Praful** [comment]
Thanks again. I'm not at my desktop but I've got my laptop and the message isn't appearing in vim. The unhandled event loop message does still appear in `ipython`. Were you referring to the `ipython` message or the vim warnings or both when you said that the last update had fixed the warnings?

My initial view was that putting `ipython` in vim `insert` mode would allow `vimtk` to paste lines but that isn't the case.

In the meantime, I can start `ipython` with the following command line to put it into emacs mode:

```
ipython --TerminalInteractiveShell.editing_mode='emacs'
```
If you change `emacs` to `vi` that will start `ipython` in `vi` mode without having to edit the config file.

Apart from the unhandled exception in event loop, this is looking very useful!

Thanks again
Praful

**Comment by Praful** [comment]
Further to my previous message, I've found the cause of the event loop exception. There is a bug in an  package used by `ipython` as described here: https://github.com/ipython/ipython/issues/12049.

**Comment by Erotemic** [comment]
Closing. If this is still an issue, please reopen.
